num1= int(input("Enter the first number: "))
num2= int(input("Enter the second number: "))
add=int(num1+num2)
sub=int(num1-num2)
mul=int(num1*num2)
div=(num1/num2)
print("Addition:", add)
print("Addition:", sub)
print("Addition:", mul)
print("Addition:", div)
